version: "3.7"

networks:
  mqtt-net:
    driver: bridge

services:

  zookeeper:
      image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
      networks:
        - mqtt-net
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ALLOW_ANONYMOUS_LOGIN: yes
      ports:
        - 22181:2181
      volumes:
        - zookeeper_mqtt_data:/bitnami
      profiles: ["kafka"]

  kafka:
    image: kafka_with_prom_exporter:${KAFKA_VRESION}
    networks:
        - mqtt-net
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
      - 7075:7075
    volumes:
      - kafka_mqtt_data:/bitnami
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      METRICS_JMX_ENABLED: true
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent-0.17.2.jar=7075:/usr/app/prom-jmx-agent-config.yml
    profiles: ["kafka"]

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    networks:
        - mqtt-net
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first_connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    volumes:
      - kafka_ui_mqtt_data:/etc/kafkaui
    depends_on:
      - kafka
      - connect
    profiles: ["kafka"]
    
  connect:
    image: kafka_connect_mqtt:${KAFKA_CONNECT_VERSION}
    container_name: connect
    networks:
      - mqtt-net
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    profiles: ["kafka"]
    
  schema-registry:
    image: confluentinc/cp-schema-registry:${SCHEMA_REGISTRY_VERSION}
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: http
    networks:
      - mqtt-net
    profiles: ["kafka"]

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: iot
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_mqtt_data:/var/lib/mysql
    networks:
      - mqtt-net
    profiles: ["kafka"]

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom_exporter/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - mqtt-net
    #depends_on:
      #- kafka
    profiles: ["kafka", "iot"]

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - mqtt-net
    depends_on:
      - prometheus
    volumes:
      - grafana_mqtt_data:/var/lib/grafana
    profiles: ["kafka", "iot"]

  mosquitto:
    image: mosquitto:${MOSQUITTO_VERSION}
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/etc/mosquitto/passwd
    networks:
      - mqtt-net
    profiles: ["kafka","iot"]

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_mqtt_data:/data
    ports:
      - 9000:9000
    networks:
      - mqtt-net
    profiles: ["kafka"]

  mosquitto-exporter:
    image: sapcc/mosquitto-exporter:${MOSQUITTO_EXPORTER_VERSION}
    container_name: mosquitto-exporter
    ports: 
      - 9234:9234
    networks:
      - mqtt-net  
    depends_on:
      - mosquitto
    profiles: ["kafka","iot"]
    command: --endpoint tcp://mosquitto:1883 --user meysam --pass meysam

  ksqldb:
    image: confluentinc/ksqldb-server:${KSQL_VERSION}
    hostname: ksqldb
    container_name: ksqldb
    ports:
      - 8088:8088
      - 8084:8083
    networks:
      - mqtt-net
    depends_on:
      - kafka
      - schema-registry
    #volumes:
     # - mqtt_ksqldb_data:/opt/ksqldb-udfs
    environment:
      KSQL_HOST_NAME: ksqldb
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: true
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: true
      KSQL_CONFIG_DIR: "/etc/ksqldb"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksqldb/log4j.properties"
      KSQL_CONNECT_URL: http://connect:8083
      KSQL_KSQL_SERVICE_ID: ksqldb-kafka-connect
      KSQL_KSQL_CONNECT_WORKER_CONFIG: /etc/ksqldb/connect.properties
      KSQL_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: 'ksqldb'
      KSQL_CONNECT_REST_PORT: 8083
      KSQL_CONNECT_GROUP_ID: kafka-connect
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      KSQL_CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_PLUGIN_PATH: '/usr/share/kafka/plugins/'
      #KSQL_KSQL_EXTENSION_DIR: /opt/ksqldb-udfs
    profiles: ["kafka","iot"]

volumes:
  zookeeper_mqtt_data:
    driver: local
  kafka_mqtt_data:
    driver: local
  kafka_ui_mqtt_data:
    driver: local
  mysql_mqtt_data:
    driver: local
  grafana_mqtt_data:
    driver: local
  portainer_mqtt_data:
    driver: local
 # mqtt_ksql_cli_data:
    #driver: local
  #mqtt_ksqldb_data:
   # driver: local