version: "3.7"

networks:
  mqtt-net:
    driver: bridge

services:

  zookeeper:
      image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
      networks:
        - mqtt-net
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ALLOW_ANONYMOUS_LOGIN: yes
      ports:
        - 22181:2181
      volumes:
        - zookeeper_mqtt_data:/bitnami
      profiles: ["kafka","influx"]

  kafka:
    image: kafka_with_prom_exporter:${KAFKA_VRESION}
    networks:
        - mqtt-net
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
      - 7075:7075
    volumes:
      - kafka_mqtt_data:/bitnami
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      METRICS_JMX_ENABLED: true
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent-0.17.2.jar=7075:/usr/app/prom-jmx-agent-config.yml
    profiles: ["kafka","influx"]

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    networks:
        - mqtt-net
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first_connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    volumes:
      - kafka_ui_mqtt_data:/etc/kafkaui
    depends_on:
      - kafka
      - connect
    profiles: ["kafka","influx"]
    
  connect:
    image: kafka_connect_mqtt:${KAFKA_CONNECT_VERSION}
    container_name: connect
    hostname: connect
    networks:
      - mqtt-net
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    profiles: ["kafka","influx"]
    
  schema-registry:
    image: confluentinc/cp-schema-registry:${SCHEMA_REGISTRY_VERSION}
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: http
    networks:
      - mqtt-net
    profiles: ["kafka","influx"]

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./kafka/prom_exporter/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - mqtt-net
    profiles: ["prometheus"]

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - mqtt-net
    volumes:
      - grafana_mqtt_data:/var/lib/grafana
    profiles: ["kafka"]

  ksqldb:
    image: confluentinc/ksqldb-server:${KSQL_VERSION}
    hostname: ksqldb
    container_name: ksqldb
    ports:
      - 8088:8088
      - 8084:8083
    networks:
      - mqtt-net
    depends_on:
      - kafka
      - schema-registry
    #volumes:
     # - mqtt_ksqldb_data:/opt/ksqldb-udfs
    environment:
      KSQL_HOST_NAME: ksqldb
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: true
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: true
      KSQL_CONFIG_DIR: /etc/ksqldb
      KSQL_LOG4J_OPTS: -Dlog4j.configuration=file:/etc/ksqldb/log4j.properties
      KSQL_CONNECT_URL: http://connect:8083
      #KSQL_KSQL_EXTENSION_DIR: /opt/ksqldb-udfs
    profiles: ["kafka"]

  rabbitmq:
    image: rabbitmq:3.11.23-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
      - 15675:15675
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_management rabbitmq_amqp1_0; rabbitmq-server\""
    networks:
      - mqtt-net
    volumes:
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin  
    profiles: ["kafka","iot"]

  influxdb:
      image: influxdb:2.7.1
      hostname: influxdb
      container_name: influxdb
      ports:
          - 8082:8083
          - 8086:8086
          - 8090:8090
      environment:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: admin
          DOCKER_INFLUXDB_INIT_PASSWORD: Sh!@#123
          DOCKER_INFLUXDB_INIT_ORG: iot
          DOCKER_INFLUXDB_INIT_BUCKET: init_test
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: QANAowpBjEIlwFYefIArs7gbcA9CqfAQzuHm062t840adf6lQgCmbLeqd6ZGJTrg1fWhH6ClZJJ9JywF6EyEHQ==
      networks:
        - mqtt-net
      volumes:
          - influxdb_mqtt_data:/var/lib/influxdb2
      profiles: ["kafka","influx"]

  telegraf:
    image: telegraf:1.28.1-alpine
    hostname: telegraf
    container_name: telegraf
    environment:
        influxdb_token: QANAowpBjEIlwFYefIArs7gbcA9CqfAQzuHm062t840adf6lQgCmbLeqd6ZGJTrg1fWhH6ClZJJ9JywF6EyEHQ==
    depends_on:
        - influxdb
    restart: unless-stopped
    networks:
      - mqtt-net
    volumes:
        - ./influxdb/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    profiles: ["kafka","influx"]

volumes:
  zookeeper_mqtt_data:
    driver: local
  kafka_mqtt_data:
    driver: local
  kafka_ui_mqtt_data:
    driver: local
  mysql_mqtt_data:
    driver: local
  grafana_mqtt_data:
    driver: local
  influxdb_mqtt_data:
    driver: local
